AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - com.vz::springboot-aws-serverless
Resources:
  SpringbootAwsServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.vz.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/springboot-aws-serverless-1.0.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringbootAwsServerlessApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: SpringbootAwsServerlessApi
